services:
  - type: web
    name: tarkov-tracker-api
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGURI
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /

  - type: web
    name: tarkov-tracker-client
    runtime: static
    region: oregon
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
